# Generated by Django 3.2.2 on 2021-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='baidu_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.CharField(max_length=200, verbose_name='百度重定向链接')),
            ],
        ),
        migrations.DeleteModel(
            name='baidu',
        ),
    ]
