# Generated by Django 3.2.2 on 2021-05-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0002_auto_20210515_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='baidu_model',
            new_name='baidu',
        ),
    ]
