# Generated by Django 3.2.2 on 2021-05-18 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0005_baidu_model_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='baidu_model',
            name='mid',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='jsmind的id'),
            preserve_default=False,
        ),
    ]
