# Generated by Django 3.2.2 on 2021-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0006_baidu_model_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baidu_model',
            name='parentid',
            field=models.CharField(default='root', max_length=40, verbose_name='父节点'),
        ),
    ]
