# Generated by Django 3.2.2 on 2021-05-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0007_alter_baidu_model_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='baidu_model',
            name='nodetype',
            field=models.CharField(default='a', max_length=40, verbose_name='节点类型'),
        ),
        migrations.AddField(
            model_name='baidu_model',
            name='root',
            field=models.CharField(default='root', max_length=50, verbose_name='根节点'),
        ),
    ]
