# Generated by Django 3.2.2 on 2021-05-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0008_auto_20210519_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baidu_model',
            name='nodetype',
            field=models.CharField(default='a', max_length=20, verbose_name='节点类型'),
        ),
    ]
