# Generated by Django 3.2.2 on 2021-05-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0009_alter_baidu_model_nodetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='baidu_model',
            name='a',
            field=models.CharField(default='xx', max_length=20, verbose_name='占位'),
        ),
        migrations.AddField(
            model_name='baidu_model',
            name='b',
            field=models.CharField(default='xx', max_length=20, verbose_name='占位'),
        ),
        migrations.AddField(
            model_name='baidu_model',
            name='c',
            field=models.CharField(default='xx', max_length=20, verbose_name='占位'),
        ),
        migrations.AddField(
            model_name='baidu_model',
            name='d',
            field=models.CharField(default='xx', max_length=20, verbose_name='占位'),
        ),
        migrations.AddField(
            model_name='baidu_model',
            name='e',
            field=models.CharField(default='xx', max_length=20, verbose_name='占位'),
        ),
        migrations.AddField(
            model_name='baidu_model',
            name='source',
            field=models.CharField(default='unknown', max_length=20, verbose_name='链接来源'),
        ),
    ]
